### PR TITLE
Fix #89 8bit Read: Correct Range

### LINKED ISSUE #89: 8 Bit Reads: Upper Bound Broken of Scale-Up to 16-bit
As `0.996109 ~ 1-1/255` this seems to happen because of some error in upscaling 255 to 65535. So unlike mentioned in the documentation 

>  returned value will be of type int and be between 0 and 65535.

the highest value is not `65535` but `65280=65535-255`.
This bug afflicts both `read` and `dread` and all other read functions which call `read`, like scaling and interpolation, ....
I will submit a pull request shortly.

### PR DESCRIPTION
**Pull request by mxmlnkn**
Fix #89: The other appearances of `*256` seem to be some weird upscales in order to avoid floating point arithmetic. They are scaled down `/256` soon thereafter.

### CODE REVIEW

File: src/pngwriter.cc [hunk 1]
```diff
@@ -765,6 +765,14 @@ int pngwriter::read(int x, int y, int colour) const
 
 	if(bit_depth_ == 16)
 	  {
+	     /* In these cases *256 is correct, because what we actually are
```
Comment (ax3l) [inline src/pngwriter.cc]: indent / tabs ;)

File: src/pngwriter.cc [hunk 2]
```diff
@@ -787,23 +795,24 @@ int pngwriter::read(int x, int y, int colour) const
 
 	if(bit_depth_ == 8)
 	  {
+	     int const scale8To16Bit = 257;   // x/255*65535 = x*257
```
Comment (ax3l) [inline src/pngwriter.cc]: this comment is not clear to me. integer `255*65535` is `16711425` and `1/16711425` is `0`. not `*257`

Comment (ax3l) [inline src/pngwriter.cc]: what you are trying to say is: `x*65535/255 = x*257`

Comment (ax3l) [inline src/pngwriter.cc]: oh wait, I am stupid

Comment (ax3l) [inline src/pngwriter.cc]: just to make it more readable, can you please write it `x*65535/255 = x*257` ?

Comment (mxmlnkn) [inline src/pngwriter.cc]: This is a normal division slash, which well in my opinion and in the opinion of the C++ language only affects the very next number, not the rest of the line. I didn't want to write your version, because I imagine it this way:
  1. scale down by `/255` to reach `[0,1.0]`
  2. scale up by `65535`
You self-assigned this pull request, does that mean you will do the changes yourself or does that only mean you will peer review it?

File: src/pngwriter.cc (hunk 1 above)
Comment (mxmlnkn) [inline src/pngwriter.cc]: yep .. I wanted to keep the style of the sourring indentation, because I just don't get the original indentation. I'm not even sure that tabs are 3 spaces... There are so many contradicting indentations. Tabs should be completely changed in another commit in my opinion.

Comment (ax3l) [inline src/pngwriter.cc]: I know it's fantastic, isn't it? ;) I was just wondering since line 1 of this block was different then the rest

File: src/pngwriter.cc (hunk 2 above)
Comment (ax3l) [inline src/pngwriter.cc]: sounds legit. be aware you reach [0,1] and not float.

self assign: just means I review it :)

**Comment by ax3l** [comment]
Can you add a test for that? Would be great if this was covered.

**Comment by ax3l** [comment]
Pls keep the test short, not more then 20 lines pls.

**Comment by ax3l** [comment]
a wait, I will add a test in an independent PR

**Comment by ax3l** [comment]
After #96 was merged to `dev`, please
- rebase against `dev`
- uncomment the following two lines in `.travis.yml`:
  - ./blackwhite bw_8bit_rgb_20x20.png
  - ./blackwhite bw_8bit_rgba_20x20.png

**Comment by mxmlnkn** [comment]
rebased

**Comment by ax3l** [comment]
Awesome, ty!

**Comment by ax3l** [comment]
After merging, `dread` and `read` deliver the following values for white of a 8 bit png:

```
dread val = 257
read val = 65535
```

Needs more work, will revert for now.

**Comment by ax3l** [comment]
hm, will fix in a follow-up.

**Comment by ax3l** [comment]
the general question is if a 8 bit read should return something in the range of [0; 255] or if casting it up to 16 bit is a good idea.

nevertheless, since pngwriter only writes 16bit pngs right now this might be ok.

**Comment by ax3l** [comment]
`readHSV` might need an update, too.

**Comment by mxmlnkn** [comment]
> the general question is if a 8 bit read should return something in the range of [0; 255] or if casting it up to 16 bit is a good idea.

This is becoming a rather large change, if the discussion shifts to the internal format ... I didn't expect this.

If we are talking about the internal format, I would propose making the internal data buffer bare. In my program we could save a tad by not having to copy the whole image data with `getPixel`, then process it, then copy it back with `plot`

**Comment by ax3l** [comment]
fixed it already. currently everything ends up 16bit in pngwriter.

**Comment by ax3l** [comment]
internal storage refactoring is a task documented in #36 for an other time.

File: src/pngwriter.cc [hunk 3]
```diff
@@ -765,6 +765,14 @@ int pngwriter::read(int x, int y, int colour) const
...
 	if(bit_depth_ == 16)
 	  {
+	     /* In these cases *256 is correct, because what we actually are
+          * doing is bitshifting by 8 bit and then appending the next lower
+          * 8 bit.
+          * These lines are inefficient. Bitshifting and bitwise anding may
+          * have better performance than multiplication and addition.
+          * We could also just convert (unsigned char*) to (uint16_t*).
+          * If the open file function does it in the same way, then this
+          * method makes no assumptions about platform endianness */
```
Comment (pkohut) [inline src/pngwriter.cc]: Per PNG spec, big endian
http://www.w3.org/TR/2003/REC-PNG-20031110/#7Integers-and-byte-order
